version: '3.8'
services:
    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - web
        networks: 
            - nginx_network
    web:
        build: .
        volumes: 
            - .:/app 
        environment:
            IS_DEBUG: ${IS_DEBUG}
            STOCKS_PRJ_DJANGO_SECRET: ${STOCKS_PRJ_DJANGO_SECRET}
            ALLOWED_HOSTS: ${ALLOWED_HOSTS}
        networks: 
            - nginx_network
networks:
    nginx_network:
        driver: bridge